"""movement.py: Link's movement at 60 against 30 by the stick's magnitude and angle (the owner's note N4:
"walking in all directions, in circles, at different analog stick positions and speeds ... 100% accurate").

  movement.py gen                  writes the routes (tools/reference/routes/move*-100.txt) from SUITES below
  movement.py cmp DIR ROUTE        DIR/30 and DIR/60 from tools/sixty/run.sh ROUTE DIR with
                                   WWHD_STATE_TRACK=168,476 (Link, the camera): per segment of the route
  movement.py ticks DIR ROUTE SEG  one segment (or FROM-TO) tick by tick: 30's tick, 60's whole and half frames

Each route warps to Gohma's room (M_DragB, empty on the 100% save: the owner's test room, N10/N11), puts Link
on its floor and plays segments: the left stick held at a position of its own (the input script's LS=x,y),
let go, turned round in circles, flicked to the other side. A segment's numbers, 30 against 60 (30's tick k
paired with the 60 run's half frame that holds that tick's state, key 2k+1 or 2k-1, as predeploy.sh does):
  moved   how far Link went in the segment (its path, per tick), 30 and 60
  top     his fastest tick (units a tick), 30 and 60; ramp: the ticks to 90% of 30's top speed
  apart   where he ends against 30's, from where each began the segment (so earlier drift doesn't count)
  head    his facing (shape angle y) against 30's: the largest gap in the segment, in degrees
  cam     the camera's control angle (+0x2B4, what the stick turns by) against 30's at the segment's end
  even    at 60, the whole step's move over the half step's (1.00: evenly spaced frames), while moving
  eye     the camera's eye (+0x264) from Link against 30's: the largest gap in the segment
  jerk    the camera eye's largest change of move from one frame to the next: 30's a tick, 60's a frame x 2
          (a move that changes at once, as 30's, reads the same; spread over the tick's frames less; a jolt
          that 30 hasn't, or a bounce, more)
The camera turns the stick (Link's heading is the stick's angle + the camera's), so a heading gap with the
camera's gap alike is the camera's. Output: numbers only (no game data); the runs stay on the worker.
"""
import math
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROUTES = os.path.join(HERE, "..", "..", "reference", "routes")
sys.path.insert(0, os.path.join(HERE, ".."))

START = 1090        # Link's control after the warp (f920) and his walk in (to -1534,1,909, facing the room's middle)
HEAD = """# Route: {title}.
# Session top, the owner's notes N4 and N2; generated by tools/sixty/tests/movement.py gen (don't edit: change
# SUITES there). Gohma's room (M_DragB, empty on the 100% save), Link on its floor; the left stick
# at positions of its own (LS=x,y: right and up are +). "#seg FRAME NAME" lines start movement.py cmp's segments.
#env WWHD_DEBUG_STAGE=920:M_DragB,0,0,-1
420 A 5        # title screen
540 A 5        # Controller Selection
660 A 5        # File Selection: Quest Log 1
780 A 5        # Start; the warp at f920
"""


def stick(mag, deg):
    """The stick at a magnitude and an angle (0 up, 90 right)."""
    r = math.radians(deg)
    return f"LS={mag * math.sin(r):.4f},{mag * math.cos(r):.4f}"


def hold(mag, deg, frames, rest):
    """Held at one position, then let go."""
    return [(0, stick(mag, deg), frames)], frames + rest


def circle(mag, period, turns, rest, sign=1):
    """Turned round: a full circle every PERIOD frames, TURNS times (sign -1: the other way)."""
    n = int(period * turns)
    return [(i, stick(mag, sign * 360.0 * i / period), 1) for i in range(n)], n + rest


def flick(mag, deg1, deg2, frames, rest):
    """Held one way, then at once another (a turn: 180 is a skid)."""
    return [(0, stick(mag, deg1), frames), (frames, stick(mag, deg2), frames)], 2 * frames + rest


def weave(mag, deg, amp, every, frames, rest):
    """Swung from side to side (deg +- amp) every EVERY frames."""
    return [(i, stick(mag, deg + (amp if (i // every) % 2 else -amp)), 1) for i in range(frames)], frames + rest


def jump(deg, hops=1, every=20):
    """L-targeting (ZL held) with the stick to one side (or back), A: a side jump (back: a backflip)."""
    n = 10 + hops * every
    return [(0, "ZL", n), (4, stick(1.0, deg), n - 4)] + [(8 + i * every, "A", 3) for i in range(hops)], n + 30


def roll(frames=30, at=15):
    """Running (the stick up), A: a forward roll."""
    return [(0, stick(1.0, 0), frames), (at, "A", 3)], frames + 30


def strafe(deg, frames=40):
    """L-targeting, the stick to one side: a sidestep walk."""
    return [(0, "ZL", frames + 4), (4, stick(1.0, deg), frames)], frames + 30


# each suite: (title, [(name, segment)]); the stick at magnitudes 0.15-1 (WWHD's walk turns into a run part
# way), up and back down again so Link stays near the middle of the room
SUITES = {
    "moveramp": ("Link's walk and run from a standstill at stick magnitudes 0.15 to 1, up then back down", [
        (f"{d} {m:.2f}", hold(m, a, 45, 30)) for m in (0.15, 0.3, 0.45, 0.6, 0.75, 0.9, 1.0)
        for d, a in (("up", 0), ("down", 180))]),
    "moveangle": ("Link's walk at eight stick angles, full and half way (two octagons)", [
        (f"{a:3d} {m:.1f}", hold(m, a, 30, 20)) for m in (1.0, 0.5) for a in range(0, 360, 45)]),
    "movecircle": ("Link in circles: the stick turned round at magnitudes 1, 0.6 and 0.35, both ways, slow and fast", [
        ("circle 1.0 /60 cw", circle(1.0, 60, 2, 30)),
        ("circle 1.0 /60 ccw", circle(1.0, 60, 2, 30, -1)),
        ("circle 0.6 /90 cw", circle(0.6, 90, 1.5, 30)),
        ("circle 0.35 /90 ccw", circle(0.35, 90, 1.5, 30, -1)),
        ("circle 1.0 /24 cw", circle(1.0, 24, 4, 30)),
        ("circle 0.5 /24 ccw", circle(0.5, 24, 4, 30, -1))]),
    "moveturn": ("Link's turns: the stick flicked 180, 90 and 135 degrees at full and half, and weaving", [
        ("flick 180 1.0", flick(1.0, 0, 180, 30, 30)),
        ("flick 180 0.5", flick(0.5, 0, 180, 30, 30)),
        ("flick 90 1.0", flick(1.0, 0, 90, 30, 30)),
        ("flick -90 1.0", flick(1.0, 90, 0, 30, 30)),
        ("flick 135 1.0", flick(1.0, 180, 315, 30, 30)),
        ("weave 1.0 +-30 /6", weave(1.0, 0, 30, 6, 60, 30)),
        ("weave 0.6 +-45 /10", weave(0.6, 180, 45, 10, 60, 30))]),
    "movejump": ("L-targeting: side jumps, backflips, sidesteps and a roll, and the camera", [
        ("sidejump right", jump(90)),
        ("sidejump left", jump(270)),
        ("sidejump right x3", jump(90, 3)),
        ("sidejump left x3", jump(270, 3)),
        ("backflip", jump(180)),
        ("strafe right", strafe(90)),
        ("strafe left", strafe(270)),
        ("roll", roll())]),
}


def gen():
    for name, (title, segs) in SUITES.items():
        lines, f = [HEAD.format(title=title)], START
        for label, (steps, length) in segs:
            lines.append(f"#seg {f} {label}\n")
            lines += [f"{f + i} {s} {n}\n" for i, s, n in steps]
            f += length
        lines.append(f"#seg {f} end\n")
        path = os.path.join(ROUTES, f"{name}-100.txt")
        with open(path, "w") as out:
            out.writelines(lines)
        print(f"{path}: {len(segs)} segments, f{START}-{f} (route_info frames: {f + 10})")


def cmp(d, route):
    import compare
    segs = []
    for line in open(os.path.join(ROUTES, f"{route}-100.txt")):
        if line.startswith("#seg "):
            _, f, label = line.rstrip("\n").split(" ", 2)
            segs.append((int(f), label))

    def tracks(path):
        T = compare.load_track(path)
        out = {}
        for k in T:
            out.setdefault(k[0], {}).update(T[k])
        return out
    A, B = tracks(os.path.join(d, "30", "track.bin")), tracks(os.path.join(d, "60", "track.bin"))
    la, lb, ca, cb = A.get(168, {}), B.get(168, {}), A.get(476, {}), B.get(476, {})
    pos = lambda x: struct.unpack(">3f", x[0x314:0x320])
    s16 = lambda x, o: struct.unpack(">h", x[o:o + 2])[0]
    act = lambda x: struct.unpack(">I", x[0x65F0:0x65F4])[0]
    ang = lambda a, b: ((a - b + 32768) % 65536 - 32768) * 360 / 65536
    # the pairing: 60's key 2k+1 or 2k-1, whichever Link's path matches best (predeploy.sh)
    def paired(off):
        ts = [t for t in sorted(la) if t % 2 == 0 and t + off in lb and t >= 2 * START]
        return sum(math.dist(pos(la[t]), pos(lb[t + off])) for t in ts) / max(len(ts), 1)
    # these routes all start alike (the warp at f920, the walk in): their 60 runs hold tick k at key 2k+1 (the side
    # jumps' A lands on 30's tick there); MOVE_OFF=best picks it by Link's path as predeploy.sh does
    off = min((1, -1), key=paired) if os.environ.get("MOVE_OFF") == "best" else int(os.environ.get("MOVE_OFF", "1"))
    print(f"{route}: 30 against 60 (60's key 2k{off:+d}); Link {len(la)} and {len(lb)} track records")
    print(f"{'segment':22s} {'moved 30/60':>15s} {'top 30/60':>11s} {'t90':>7s} {'apart':>6s} {'head':>6s} {'cam':>6s} {'even':>5s} {'eye':>6s} {'jerk 30/60':>13s}  actions")
    for (f0, label), (f1, _) in zip(segs, segs[1:]):
        ks = [k for k in range(f0, f1 + 1) if 2 * k in la and 2 * k + off in lb]
        if len(ks) < 2:
            print(f"{label:22s} no ticks"); continue
        pa = [pos(la[2 * k]) for k in ks]
        pb = [pos(lb[2 * k + off]) for k in ks]
        sa = [math.dist(p, q) for p, q in zip(pa, pa[1:])]
        sb = [math.dist(p, q) for p, q in zip(pb, pb[1:])]
        top_a, top_b = max(sa), max(sb)
        t90 = lambda s: next((i + 1 for i, v in enumerate(s) if v >= 0.9 * top_a), None)
        da = [x - y for x, y in zip(pa[-1], pa[0])]
        db = [x - y for x, y in zip(pb[-1], pb[0])]
        apart = math.dist(da, db)
        head = max(abs(ang(s16(la[2 * k], 0x32A), s16(lb[2 * k + off], 0x32A))) for k in ks)
        ke = ks[-1]
        cam = (ang(s16(ca[2 * ke], 0x2B4), s16(cb[2 * ke + off], 0x2B4))
               if 2 * ke in ca and 2 * ke + off in cb else float("nan"))
        # the 60 run's two steps of each tick while he moves: the whole step's move (key 2k-1+off.. ) against the half's
        w = h = 0.0
        for k in ks[1:]:
            k0, k1, k2 = 2 * k - 2 + off, 2 * k - 1 + off, 2 * k + off
            if k0 in lb and k1 in lb and k2 in lb:
                m1, m2 = math.dist(pos(lb[k0]), pos(lb[k1])), math.dist(pos(lb[k1]), pos(lb[k2]))
                if m1 + m2 > 1.0:
                    first_is_whole = (k1 % 2 == 0)
                    w += m1 if first_is_whole else m2
                    h += m2 if first_is_whole else m1
        even = w / h if h else float("nan")
        # the camera's eye (+0x264) from Link: the largest gap with 30's; its jerk, the largest change of its
        # move from one frame to the next, 60's x 2 against 30's a tick (a change at once, as 30's: the same)
        eye = lambda x: struct.unpack(">3f", x[0x264:0x270])
        rel = lambda C, L, t: [e - q for e, q in zip(eye(C[t]), pos(L[t]))] if t in C and t in L else None
        gaps = [math.dist(ra, rb) for ra, rb in ((rel(ca, la, 2 * k), rel(cb, lb, 2 * k + off)) for k in ks) if ra and rb]
        eyegap = max(gaps) if gaps else float("nan")
        def jerk(C, keys):
            e = [eye(C[t]) for t in keys if t in C]
            v = [[q - p for p, q in zip(a, b)] for a, b in zip(e, e[1:])]
            return max((math.dist(a, b) for a, b in zip(v, v[1:])), default=float("nan"))
        ja = jerk(ca, [2 * k for k in ks])
        jb = 2 * jerk(cb, range(2 * ks[0] + off, 2 * ks[-1] + off + 1))
        acts = lambda L, sel: [act(L[sel(k)]) for k in ks]
        aa, ab = acts(la, lambda k: 2 * k), acts(lb, lambda k: 2 * k + off)
        changes = lambda s: [(ks[i], v) for i, v in enumerate(s) if i == 0 or v != s[i - 1]]
        cha, chb = changes(aa), changes(ab)
        diff = "same" if [v for _, v in cha] == [v for _, v in chb] and all(abs(x[0] - y[0]) <= 0 for x, y in zip(cha, chb)) \
            else " ".join(f"{v:02x}@{k}" for k, v in cha) + " | " + " ".join(f"{v:02x}@{k}" for k, v in chb)
        t90s = f"{t90(sa) or '-'}/{t90(sb) or '-'}"
        print(f"{label:22s} {sum(sa):7.1f}/{sum(sb):7.1f} {top_a:5.2f}/{top_b:5.2f} {t90s:>7s} {apart:6.2f} {head:6.2f} {cam:6.2f} {even:5.2f}"
              f" {eyegap:6.2f} {ja:6.2f}/{jb:6.2f}  {diff}")


def ticks(d, route, which):
    """Per tick of one segment: Link at 30 (tick k) and at 60 (the whole key 2k, the half 2k+1): his place's
    move, facing, speedF, mNormalSpeed and action; the camera's control angle and eye."""
    import compare
    segs = [(int(l.split(" ", 2)[1]), l.rstrip("\n").split(" ", 2)[2])
            for l in open(os.path.join(ROUTES, f"{route}-100.txt")) if l.startswith("#seg ")]
    if which[:1].isdigit():                       # or frames: FROM-TO
        f0, f1 = map(int, which.split("-"))
    else:
        i = next(i for i, (_, label) in enumerate(segs) if label == which)
        f0, f1 = segs[i][0], segs[i + 1][0]

    def tracks(path):
        T = compare.load_track(path)
        out = {}
        for k in T:
            out.setdefault(k[0], {}).update(T[k])
        return out
    A, B = tracks(os.path.join(d, "30", "track.bin")), tracks(os.path.join(d, "60", "track.bin"))
    f = lambda x, o: struct.unpack(">f", x[o:o + 4])[0]
    p3 = lambda x, o: struct.unpack(">3f", x[o:o + 12])
    s16 = lambda x, o: struct.unpack(">h", x[o:o + 2])[0]
    act = lambda x: struct.unpack(">I", x[0x65F0:0x65F4])[0]

    def row(L, C, t, prev):
        if t not in L:
            return "-"
        x = L[t]
        mv = math.dist(p3(x, 0x314), p3(L[prev], 0x314)) if prev in L else float("nan")
        c = C.get(t)
        cam = f"{s16(c, 0x2B4) & 0xFFFF:04x} {math.dist(p3(c, 0x264), p3(L[t], 0x314)):7.1f}" if c else "-"
        return (f"mv {mv:6.2f} face {s16(x, 0x32A) & 0xFFFF:04x} sF {f(x, 0x370):6.2f} nS {f(x, 0x6A14):6.2f}"
                f" a {act(x):02x} cam {cam}")
    for k in range(f0 - 2, f1 + 1):
        print(f"{k:5d} 30: {row(A[168], A.get(476, {}), 2 * k, 2 * k - 2)}")
        print(f"      60w {row(B[168], B.get(476, {}), 2 * k, 2 * k - 1)}")
        print(f"      60h {row(B[168], B.get(476, {}), 2 * k + 1, 2 * k)}")


if __name__ == "__main__":
    if sys.argv[1:2] == ["gen"]:
        gen()
    elif sys.argv[1:2] == ["cmp"] and len(sys.argv) == 4:
        cmp(sys.argv[2], sys.argv[3])
    elif sys.argv[1:2] == ["ticks"] and len(sys.argv) == 5:
        ticks(sys.argv[2], sys.argv[3], sys.argv[4])
    else:
        sys.exit(__doc__)
